name: README.md Metrics
on:
  schedule: 
    - cron: "0 * * * *"
  push: 
    branches:
      - main
  workflow_dispatch:
jobs:
  header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          user: jamesblanksby
          repositories_affiliations: owner,organization_member
          template: classic
          base: header
          config_timezone: Europe/London
          filename: lib/header.svg
  isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          user: jamesblanksby
          repositories_affiliations: owner,organization_member
          template: classic
          base: header
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Europe/London
          filename: lib/isocalendar.svg